author: Mitchell Riley
description: >- 
  Mitchell Riley's blog with a focus on numerical analysis
email: mitchr@mitchr.dev
github_url: https://github.com/mitchr
linkedin_url: https://linkedin.com/in/mitchell-riley-0917b814a

# Build settings
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
